// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaApp.Database.Context;

namespace PizzaApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200427151952_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PizzaApp.Database.Models.Adresses", b =>
                {
                    b.Property<int>("NumAdresse")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Num_Adresse")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresse")
                        .HasColumnName("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumQuartier")
                        .HasColumnName("Num_Quartier")
                        .HasColumnType("int");

                    b.HasKey("NumAdresse");

                    b.HasIndex("NumQuartier");

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("PizzaApp.Database.Models.BonLiv", b =>
                {
                    b.Property<int>("NumBonLiv")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Num_Bon_Liv")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NumCdeCli")
                        .HasColumnName("Num_Cde_Cli")
                        .HasColumnType("int");

                    b.Property<int?>("Num_Fact")
                        .HasColumnName("Num_Fact")
                        .HasColumnType("int");

                    b.HasKey("NumBonLiv");

                    b.HasIndex("NumCdeCli");

                    b.HasIndex("Num_Fact");

                    b.ToTable("Bon_Liv");
                });

            modelBuilder.Entity("PizzaApp.Database.Models.CataloguePizza", b =>
                {
                    b.Property<int>("NumPizza")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Num_Pizza")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomPizza")
                        .HasColumnName("Nom_Pizza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrixPizza")
                        .HasColumnName("Prix_Pizza")
                        .HasColumnType("int");

                    b.Property<int>("TaillePizza")
                        .HasColumnName("Taille_Pizza")
                        .HasColumnType("int");

                    b.HasKey("NumPizza");

                    b.ToTable("Catalogue_Pizza");
                });

            modelBuilder.Entity("PizzaApp.Database.Models.CdeCli", b =>
                {
                    b.Property<int>("numCdeCli")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Num_Cde_Cli")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCde")
                        .HasColumnName("Date_Cde")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LivreEmporte")
                        .HasColumnName("Livre_Emporte")
                        .HasColumnType("bit");

                    b.Property<int>("NumCli")
                        .HasColumnName("Num_Cli")
                        .HasColumnType("int");

                    b.HasKey("numCdeCli");

                    b.HasIndex("NumCli");

                    b.ToTable("Cde_Cli");
                });

            modelBuilder.Entity("PizzaApp.Database.Models.Client", b =>
                {
                    b.Property<int>("NumCli")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Num_Client")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresse")
                        .HasColumnName("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomCli")
                        .HasColumnName("Nom_Cli")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NumCli");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("PizzaApp.Database.Models.DetailLiv", b =>
                {
                    b.Property<int>("NumDetailBonLiv")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Num_Detail_Bon_Liv")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdresseLiv")
                        .HasColumnName("Adresse_Liv")
                        .HasColumnType("int");

                    b.Property<int>("NumBonLiv")
                        .HasColumnName("Num_Bon_Liv")
                        .HasColumnType("int");

                    b.Property<int>("NumLiv")
                        .HasColumnName("Num_Liv")
                        .HasColumnType("int");

                    b.HasKey("NumDetailBonLiv");

                    b.HasIndex("AdresseLiv");

                    b.HasIndex("NumBonLiv");

                    b.HasIndex("NumLiv");

                    b.ToTable("Detail_Liv");
                });

            modelBuilder.Entity("PizzaApp.Database.Models.Fabrication", b =>
                {
                    b.Property<int>("NumFab")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Num_Fab")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateFab")
                        .HasColumnName("Date_Fab")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumPizza")
                        .HasColumnName("Num_Pizza")
                        .HasColumnType("int");

                    b.Property<int>("QuantFab")
                        .HasColumnName("Quant_Fab")
                        .HasColumnType("int");

                    b.HasKey("NumFab");

                    b.HasIndex("NumPizza");

                    b.ToTable("Fabrication");
                });

            modelBuilder.Entity("PizzaApp.Database.Models.FactCliBonLiv", b =>
                {
                    b.Property<int>("NumFAct")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Num_Fact")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateFactCli")
                        .HasColumnName("Date_Fact_Cli")
                        .HasColumnType("datetime2");

                    b.Property<int>("MontantTotal")
                        .HasColumnName("Montant_Total")
                        .HasColumnType("int");

                    b.Property<int>("NumCli")
                        .HasColumnName("Num_Cli")
                        .HasColumnType("int");

                    b.HasKey("NumFAct");

                    b.HasIndex("NumCli");

                    b.ToTable("Fact_Cli_Bon_Liv");
                });

            modelBuilder.Entity("PizzaApp.Database.Models.LigneCdeCli", b =>
                {
                    b.Property<int>("NumLigneCde")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Num_Ligne_Cde")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NumCdeCli")
                        .HasColumnName("Num_Cde_Cli")
                        .HasColumnType("int");

                    b.Property<int>("NumPizza")
                        .HasColumnName("Num_Pizza")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnName("Quantite")
                        .HasColumnType("int");

                    b.HasKey("NumLigneCde");

                    b.HasIndex("NumCdeCli");

                    b.HasIndex("NumPizza");

                    b.ToTable("Ligne_Cde_Cli");
                });

            modelBuilder.Entity("PizzaApp.Database.Models.Livraison", b =>
                {
                    b.Property<int>("NumLiv")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Num_Liv")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateArrive")
                        .HasColumnName("Date_Arrive")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDepart")
                        .HasColumnName("Date_Depart")
                        .HasColumnType("datetime2");

                    b.HasKey("NumLiv");

                    b.ToTable("Livraison");
                });

            modelBuilder.Entity("PizzaApp.Database.Models.Livreur", b =>
                {
                    b.Property<int>("NumLiv")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Num_Liv")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomLivreur")
                        .HasColumnName("Nom_Livreur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumQuartier")
                        .HasColumnName("Num_Quartier")
                        .HasColumnType("int");

                    b.HasKey("NumLiv");

                    b.HasIndex("NumQuartier");

                    b.ToTable("Livreur");
                });

            modelBuilder.Entity("PizzaApp.Database.Models.PaiementCli", b =>
                {
                    b.Property<int>("NumPieceCompt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Num_Piece_Compt")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnName("Date_Paiement")
                        .HasColumnType("datetime2");

                    b.Property<int>("MontantPaiement")
                        .HasColumnName("Montant_Paiement")
                        .HasColumnType("int");

                    b.Property<int>("NumFact")
                        .HasColumnName("Num_Fact")
                        .HasColumnType("int");

                    b.HasKey("NumPieceCompt");

                    b.HasIndex("NumFact");

                    b.ToTable("Paiement_Cli");
                });

            modelBuilder.Entity("PizzaApp.Database.Models.Quartier", b =>
                {
                    b.Property<int>("NumQuartier")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Num_Quartier")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nom_Quartier")
                        .HasColumnName("Nom_Quartier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NumQuartier");

                    b.ToTable("Quartier");
                });

            modelBuilder.Entity("PizzaApp.Database.Models.Adresses", b =>
                {
                    b.HasOne("PizzaApp.Database.Models.Quartier", "Quartier")
                        .WithMany()
                        .HasForeignKey("NumQuartier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaApp.Database.Models.BonLiv", b =>
                {
                    b.HasOne("PizzaApp.Database.Models.CdeCli", "CdeCli")
                        .WithMany()
                        .HasForeignKey("NumCdeCli")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaApp.Database.Models.FactCliBonLiv", "FactCliBonLiv")
                        .WithMany()
                        .HasForeignKey("Num_Fact");
                });

            modelBuilder.Entity("PizzaApp.Database.Models.CdeCli", b =>
                {
                    b.HasOne("PizzaApp.Database.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("NumCli")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaApp.Database.Models.DetailLiv", b =>
                {
                    b.HasOne("PizzaApp.Database.Models.Adresses", "Adresses")
                        .WithMany()
                        .HasForeignKey("AdresseLiv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaApp.Database.Models.BonLiv", "BonLiv")
                        .WithMany()
                        .HasForeignKey("NumBonLiv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaApp.Database.Models.Livraison", "Livraison")
                        .WithMany()
                        .HasForeignKey("NumLiv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaApp.Database.Models.Fabrication", b =>
                {
                    b.HasOne("PizzaApp.Database.Models.CataloguePizza", "CataloguePizza")
                        .WithMany()
                        .HasForeignKey("NumPizza")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaApp.Database.Models.FactCliBonLiv", b =>
                {
                    b.HasOne("PizzaApp.Database.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("NumCli")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaApp.Database.Models.LigneCdeCli", b =>
                {
                    b.HasOne("PizzaApp.Database.Models.CdeCli", "CdeCli")
                        .WithMany()
                        .HasForeignKey("NumCdeCli")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaApp.Database.Models.CataloguePizza", "CataloguePizza")
                        .WithMany()
                        .HasForeignKey("NumPizza")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaApp.Database.Models.Livreur", b =>
                {
                    b.HasOne("PizzaApp.Database.Models.Quartier", "Quartier")
                        .WithMany()
                        .HasForeignKey("NumQuartier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaApp.Database.Models.PaiementCli", b =>
                {
                    b.HasOne("PizzaApp.Database.Models.FactCliBonLiv", "FactCliBonLiv")
                        .WithMany()
                        .HasForeignKey("NumFact")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
